# This is a basic workflow to help you get started with Actions

name: jest

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  jest:
    runs-on: ubuntu-latest
    steps:
      - name: Run Jest
        uses: stefanoeb/jest-action@1.0.4
